[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "formatflick"
version = "0.1.0"
description = "Python module for interchanging file formats"
url = "https://github.com/cohitherewer/formatFlick-engine"
authors = [{name="Abhinaba Chakraborty",email="abhinabacr4@gmail.com"}]
maintainers = [
  {name = "Abhinaba Chakraborty", email = "brett@example.com"}
]
readme = "README.md"
license = {file="BSD 3-clause"}
dynamic = ["version"]
dependencies = [
  "pandas"
]
classifiers = [
  "Development Status :: 1 - Planning",
  "Programming Language :: Python"
]
requires-python = ">=3.6"
keywords = ["json", "csv", "xml", "format", "python3"]

[project.urls]
HHomepage = "https://example.com"
Documentation = "https://readthedocs.org"
Repository = "https://github.com/me/spam.git"
Issues = "https://github.com/me/spam/issues"
Changelog = "https://github.com/me/spam/blob/master/CHANGELOG.md"

[project.scripts]

[project.gui-scripts]

[project.entry-points."spam.magical"]
