name: Unit Testing

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pandas

      - name: Unit Testing
        run: |
          python3 -m unittest discover
        working-directory: ${{ github.workspace }}

      - name: Check GitHub Workspace
        run: |
            echo "GitHub Workspace Directory: ${{ github.workspace }}"
            ls -al