name: Unit Testing

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas --user

      - name: Unit Testing
        run: |
          python -m unittest discover