name: Unit Testing

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip3 install --upgrade pip
          pip3 install pandas
          pip3 install pytest

      - name: Unit Testing
        run: |
          pytest
